### ISSUE TITLE
[Bug] Uncaught TypeError: document.getElementById(...) is null

### ISSUE THREAD

**Issue by brunobord** [s427/MARL#1]
* version: main branch (5162b9d)
* Browser: Firefox 132.0.2 on MacOS Sonoma 14.7.1

I've just downloaded my archive as a zip format. Using a simple static server (`python3 -m http.server`)
Tried to upload it on the page using both the drag'n'drop or the "Parcourir" button.

The application displayed a "Loading…" message and then… nothing. I've waited a bit, but finally fired up the Dev Console and saw the following error: `Uncaught TypeError: document.getElementById(...) is null"

It points at `/js/main.js:989` (code is: `document.getElementById("toots").scrollTop = 0;`), in the `scrollTootsToTop` function.

I'm not sure of what's going on here. Does that mean that the archive is corrupted? hasn't got the right format? is it a bug on MARL side?

**Comment by s0llvan** [comment]
I was able to reproduce the issue. In fact, when the archive does not contain any messages (other than replies), it does not work because this case was not accounted for by MARL.

**Comment by s427** [comment]
Thanks for looking into the issue. It's possible I did not account for this scenario. I'll have a look for a fix during the week-end.

**Comment by s427** [comment]
@s0llvan I'm not sure I understand what you mean by "the archive does not contain any messages (other than replies)". I just tried with an archive where I removed all posts from the outbox.json file (empty "orderedItems") and I did not encounter any bug. Could you give me more details about how to reproduce the issue?

**Comment by s0llvan** [comment]
I tested with two archives : the first is from an account that has never posted messages, only replies, while the second is from an account that has posted messages. I encountered the bug with the first archive, but not with the second.

**Comment by s427** [comment]
(I'd rather keep the discussion in English in case somebody who doesn't speak French finds this issue.)

> I tested with two archives : the first is from an account that has never posted messages, only replies, while the second is from an account that has posted messages. I encountered the bug with the first archive, but not with the second.

Thanks for clarifying. But regular posts and replies are structurally the same (they are all "posts" and MARL doesn't treat them differently), so I don't see how this could be the cause.

I think I may have identified a possible cause for this issue, although it is not specific to the archive content and I don't understand why it would occur only in some cases. I just pushed a fix.

Could you test again in the official online version? https://s427.github.io/MARL/
_Don't forget to refresh the page before testing._

Thanks!

**Comment by brunobord** [comment]
mmmm… doesn't seem to work. But I think it's a bit worse, since there's no more error message in the console. The "Loading" message is displayed and… nothing. :/

**Comment by brunobord** [comment]
I even tried with my ad-blocker disabled, and it didn't change anything.

**Comment by s427** [comment]
Do you know the version of Mastodon your instance is based on?

Also, is your archive file a ZIP file or GZ?

**Comment by s0llvan** [comment]
I still have the same issue, I'm using the same instance as my other archive that works (ZIP)

**Comment by brunobord** [comment]
My instance runs on the v4.3.1 (it's https://dice.camp/) and the archive is a zip file.
I've opened it without any issue, it shows the following contents:

* actor.json
* avatar.jpg
* bookmarks.json
* likes.json
* media_attachments/ (a directory with all my medias)
* outbox.json

**Comment by s427** [comment]
Ah, so you don't have a header image for your profile (only the avatar). Maybe that's it. I'll see if I can reproduce the issue.

**Comment by s427** [comment]
Could you open your `actor.json` file and tell me whether you see a line that starts with `"image"` near the end of it? (see screenshot)

![image](https://github.com/user-attachments/assets/33b06caf-15bb-4855-a159-255bf6e5cac1)

**Comment by s0llvan** [comment]
I don't have the 'image' line on my side, nor the 'icon' line, so that must surely be it because when I remove it from the working archive, the issue appears.

**Comment by s427** [comment]
Yes, I believe this time I've got it. I just pushed another fix, could you test it again please? (Don't forget to refresh the page.)

**Comment by s0llvan** [comment]
The issue is resolved on my side, thanks, it's working fine ! 😁

**Comment by brunobord** [comment]
indeed! it works!

**Comment by s427** [comment]
Glad to hear it. :) I'm closing this issue.
